apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepcoding-app.fullname" . }}
  labels:
    {{- include "keepcoding-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "keepcoding-app.selectorLabels" . | nindent 4 }}