apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keepcoding-app.fullname" . }}-secret
type: Opaque
data:
  DATABASE_URL: {{ printf "mysql+pymysql://%s:%s@%s-mariadb-headless:3306/%s" .Values.mariadb.auth.user .Values.mariadb.auth.password (include "keepcoding-app.fullname" .) .Values.mariadb.auth.database | b64enc }}