apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keepcoding-app.fullname" . }}-mariadb-secret
  labels:
    {{- include "keepcoding-app.labels" . | nindent 4 }}
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.auth.user | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.auth.database | b64enc | quote }}
