apiVersion: v1
kind: Service
metadata:
  name: {{ include "keepcoding-app.fullname" . }}-mariadb-headless
  labels:
    {{- include "keepcoding-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "keepcoding-app.mariadbSelectorLabels" . | nindent 4 }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
