apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-keepcoding
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-keepcoding
  template:
    metadata:
      labels:
        app: app-keepcoding
    spec:
      containers:
      - name: contenedor-keepcoding
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - secretRef:
            name: secret-keepcoding
        - configMapRef:
            name: configmap-keepcoding
